### ISSUE TITLE
Add region support

### ISSUE THREAD

**Issue by CaseyPeters** [seek-oss/docker-ecr-publish-buildkite-plugin#14]
It would be great if I could specify the region the ECR is located in, Our build setup has all of our builds running in US-WEST-2 but yet our ECR is located in US-EAST-1

**Comment by runk** [comment]
PR would be appreciated ;)

**Comment by 72636c** [comment]
Resolved by #20; see [v2.0.0](https://github.com/seek-oss/docker-ecr-publish-buildkite-plugin/releases/tag/v2.0.0)
