### ISSUE TITLE
Add additional_build_args to docker build command

### ISSUE THREAD

**Issue by regiswilson** [seek-oss/docker-ecr-publish-buildkite-plugin#15]
In the `docker build` line https://github.com/seek-oss/docker-ecr-publish-buildkite-plugin/blob/master/hooks/command#L131

It would be very useful to copy the great idea used in the cache plugin to specify additional arguments to `docker build`, see https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin/blob/master/hooks/pre-command#L196

The main use case is passing `--progress=plain` for setting `DOCKER_BUILDKIT=1` (see https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-command-line-build-output)

**Comment by regiswilson** [comment]
I would appreciate any feedback or comments on #17

**Comment by regiswilson** [comment]
Blocked by #18 unfortunately

**Comment by 72636c** [comment]
Published as [`v1.4.0`](https://github.com/seek-oss/docker-ecr-publish-buildkite-plugin/releases/tag/v1.4.0)
